# Pharmacogenomics Machine Learning Project
## Notebook 01: Data Exploration

### Purpose
This notebook exlores the ClinPGx datasets that will be used to build a pharmacogenomics machine learning model.

The objects of this notebook are to:
- Understand the structure of each dataset
- Identify potential merge keys
- Examine data quality
- Document missing values
- Identify duplicate records
- Understand relationships between datasets

This notebook is exploratory only.
No data cleaning or modification will be performed here.

### 1. Import Libraries

In [10]:
# Import the pandas library for reading, manipulating, and analyzing tabular data.
import pandas as pd

# Import NumPy for numerical operations.
import numpy as np

# Import Matplotlib for creating graphs and visualizations.
import matplotlib.pyplot as plt

# Import Path from pathlib to build operating system-independent file paths.
from pathlib import Path

### 2. Configure Display Settings

In [11]:
# Display every column in a DataFrame instead of truncating wide tables.
pd.set_option("display.max_columns", None)

# Allow up to 100 rows to be displayed before truncation for more context when examning datasets.
pd.set_option("display.max_rows", 100)

# Set a consistent default figure size for all plots in this notebook.
plt.rcParams["figure.figsize"] = (10, 6)

### 3. Define Data Paths

In [12]:
# Create a Path object that points to the folder containing the raw ClinPGx datasets.
DATA_PATH = Path("../data/raw")

# Create file paths for each ClinPGx dataset.
clinical_file = DATA_PATH / "clinicalVariants.tsv"
drug_file = DATA_PATH / "var_drug_ann.tsv"
phenotype_file = DATA_PATH / "var_pheno_ann.tsv"
functional_file = DATA_PATH / "var_fa_ann.tsv"

### 4. Load Datasets

In [13]:
# Read the Clinical Variants dataset into a pandas DataFrame.
clinical = pd.read_csv(clinical_file, sep="\t")

# Read the Variant Drug Annotation dataset.
drug = pd.read_csv(drug_file, sep="\t")

# Read the Variant Phenotype Annotation dataset.
phenotype = pd.read_csv(phenotype_file, sep="\t")

# Read the Functional Assay Annotation dataset.
functional = pd.read_csv(functional_file, sep="\t")

In [14]:
# Print the dimensions of each dataset: (number of rows, number of columns)
print("Clinical:", clinical.shape)
print("Drug:", drug.shape)
print("Phenotype:", phenotype.shape)
print("Functional:", functional.shape)

Clinical: (5190, 6)
Drug: (12975, 22)
Phenotype: (14490, 25)
Functional: (2153, 23)

### 5. Dataset Summary
&emsp;This information helps determine whether any columbs may require cleaning later.\
&emsp;This includes:\
&emsp;&ensp;- number of rows\
&emsp;&ensp;- number of columns\
&emsp;&ensp;- column names\
&emsp;&ensp;- data types\
&emsp;&ensp;- number of non-missing values

In [15]:
# Display summary information about the Clinical Variants dataset.
clinical.info()

<class 'pandas.DataFrame'>
RangeIndex: 5190 entries, 0 to 5189
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   variant            5190 non-null   str
 1   gene               4936 non-null   str
 2   type               5190 non-null   str
 3   level of evidence  5190 non-null   str
 4   chemicals          5190 non-null   str
 5   phenotypes         4175 non-null   str
dtypes: str(6)
memory usage: 243.4 KB

In [16]:
# Display summary information for the Variant Drug Annotation dataset.
drug.info()

<class 'pandas.DataFrame'>
RangeIndex: 12975 entries, 0 to 12974
Data columns (total 22 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Variant Annotation ID                   12975 non-null  int64
 1   Variant/Haplotypes                      12975 non-null  str
 2   Gene                                    12635 non-null  str
 3   Drug(s)                                 12975 non-null  str
 4   PMID                                    12975 non-null  int64
 5   Phenotype Category                      12951 non-null  str
 6   Significance                            12975 non-null  str
 7   Notes                                   11340 non-null  str
 8   Sentence                                12975 non-null  str
 9   Alleles                                 12436 non-null  str
 10  Specialty Population                    1339 non-null   str
 11  Metabolizer types                       805 non-null    str
 12  isPlural                                12975 non-null  str
 13  Is/Is Not associated                    12975 non-null  str
 14  Direction of effect                     8302 non-null   str
 15  PD/PK terms                             12972 non-null  str
 16  Multiple drugs And/or                   1787 non-null   str
 17  Population types                        11215 non-null  str
 18  Population Phenotypes or diseases       9701 non-null   str
 19  Multiple phenotypes or diseases And/or  567 non-null    str
 20  Comparison Allele(s) or Genotype(s)     11389 non-null  str
 21  Comparison Metabolizer types            678 non-null    str
dtypes: int64(2), str(20)
memory usage: 2.2 MB

In [17]:
# Display summary information for the Variant Phenotype Annotation dataset.
phenotype.info()

<class 'pandas.DataFrame'>
RangeIndex: 14490 entries, 0 to 14489
Data columns (total 25 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   Variant Annotation ID                           14490 non-null  int64
 1   Variant/Haplotypes                              14490 non-null  str
 2   Gene                                            14074 non-null  str
 3   Drug(s)                                         13551 non-null  str
 4   PMID                                            14490 non-null  int64
 5   Phenotype Category                              14358 non-null  str
 6   Significance                                    14490 non-null  str
 7   Notes                                           11762 non-null  str
 8   Sentence                                        14490 non-null  str
 9   Alleles                                         14005 non-null  str
 10  Specialty Population                            1538 non-null   str
 11  Metabolizer types                               659 non-null    str
 12  isPlural                                        14490 non-null  str
 13  Is/Is Not associated                            14490 non-null  str
 14  Direction of effect                             10222 non-null  str
 15  Side effect/efficacy/other                      10287 non-null  str
 16  Phenotype                                       14485 non-null  str
 17  Multiple phenotypes And/or                      6151 non-null   str
 18  When treated with/exposed to/when assayed with  13552 non-null  str
 19  Multiple drugs And/or                           3060 non-null   str
 20  Population types                                10628 non-null  str
 21  Population Phenotypes or diseases               9848 non-null   str
 22  Multiple phenotypes or diseases And/or          645 non-null    str
 23  Comparison Allele(s) or Genotype(s)             11847 non-null  str
 24  Comparison Metabolizer types                    373 non-null    str
dtypes: int64(2), str(23)
memory usage: 2.8 MB

In [18]:
# Display summary information for the Functional Assay dataset.
functional.info()

<class 'pandas.DataFrame'>
RangeIndex: 2153 entries, 0 to 2152
Data columns (total 23 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   Variant Annotation ID                           2153 non-null   int64
 1   Variant/Haplotypes                              2153 non-null   str
 2   Gene                                            2103 non-null   str
 3   Drug(s)                                         1488 non-null   str
 4   PMID                                            2153 non-null   int64
 5   Phenotype Category                              2005 non-null   str
 6   Significance                                    2153 non-null   str
 7   Notes                                           1961 non-null   str
 8   Sentence                                        2153 non-null   str
 9   Alleles                                         2146 non-null   str
 10  Specialty Population                            35 non-null     str
 11  Assay type                                      743 non-null    str
 12  Metabolizer types                               13 non-null     str
 13  isPlural                                        2153 non-null   str
 14  Is/Is Not associated                            2153 non-null   str
 15  Direction of effect                             1822 non-null   str
 16  Functional terms                                2153 non-null   str
 17  Gene/gene product                               1475 non-null   str
 18  When treated with/exposed to/when assayed with  885 non-null    str
 19  Multiple drugs And/or                           184 non-null    str
 20  Cell type                                       817 non-null    str
 21  Comparison Allele(s) or Genotype(s)             1687 non-null   str
 22  Comparison Metabolizer types                    6 non-null      str
dtypes: int64(2), str(21)
memory usage: 387.0 KB

### 6. Preview Records
This provides a quick visual inspection of the data structure and verifies that the dataset was imported correctly.

In [19]:
# Display the first five rows of the Clinical Variants dataset.
clinical.head()

,variant,gene,type,level of evidence,chemicals,phenotypes
0,"CYP2C9*1, CYP2C9*3, CYP2C9*13",CYP2C9,Metabolism/PK,1A,lornoxicam,NaN
1,rs17376848,DPYD,Toxicity,1A,capecitabine,Neoplasms
2,rs2297595,DPYD,Toxicity,1A,capecitabine,Neoplasms
3,rs1801265,DPYD,Toxicity,1A,capecitabine,Neoplasms
4,"CYP2C19*1, CYP2C19*2, CYP2C19*3",CYP2C19,Metabolism/PK,1A,dexlansoprazole,NaN

In [20]:
# Display the first five rows of the Variant Drug Annotation dataset.
drug.head()

,Variant Annotation ID,Variant/Haplotypes,Gene,Drug(s),PMID,Phenotype Category,Significance,Notes,Sentence,Alleles,Specialty Population,Metabolizer types,isPlural,Is/Is Not associated,Direction of effect,PD/PK terms,Multiple drugs And/or,Population types,Population Phenotypes or diseases,Multiple phenotypes or diseases And/or,Comparison Allele(s) or Genotype(s),Comparison Metabolizer types
0,1451834452,"CYP3A4*1, CYP3A4*17",CYP3A4,nifedipine,15634941,"Other, Metabolism/PK",not stated,in vitro expression of the recombinant CYP3A4*...,CYP3A4 *17 is associated with decreased metabo...,*17,NaN,NaN,Is,Associated with,decreased,metabolism of,NaN,NaN,NaN,NaN,*1,NaN
1,1453073660,rs2909451,DPP4,sitagliptin,39792745,Efficacy,yes,"""Patients with the rs2909451 TT genotype in th...",Genotype TT is associated with decreased respo...,TT,NaN,NaN,Is,Associated with,decreased,response to,NaN,in people with,"Other:Diabetes Mellitus, Type 2",NaN,NaN,NaN
2,1453071582,rs706795,FAIM2,"citalopram, escitalopram, fluoxetine, fluvoxam...",40054571,Efficacy,no,"""We observed nominally significant association...",Allele T is associated with increased response...,T,NaN,NaN,Is,Associated with,increased,response to,or,in people with,Other:Obsessive-Compulsive Disorder,NaN,C,NaN
3,1451138786,rs16918842,OPRK1,heroin,31940240,Dosage,no,No significant difference in allele or genotyp...,Allele T is not associated with dose of heroin...,T,NaN,NaN,Is,Not associated with,NaN,dose of,NaN,in people with,Other:Heroin Dependence,NaN,C,NaN
4,1448257202,"CYP2C9*1, CYP2C9*3",CYP2C9,warfarin,27488176,Dosage,yes,NaN,CYP2C9 *3 is associated with decreased dose of...,*3,NaN,NaN,Is,Associated with,decreased,dose of,NaN,NaN,NaN,NaN,*1/*1,NaN

In [21]:
# Display the first five rows of the Variant Phenotype Annotation dataset.
phenotype.head()

,Variant Annotation ID,Variant/Haplotypes,Gene,Drug(s),PMID,Phenotype Category,Significance,Notes,Sentence,Alleles,Specialty Population,Metabolizer types,isPlural,Is/Is Not associated,Direction of effect,Side effect/efficacy/other,Phenotype,Multiple phenotypes And/or,When treated with/exposed to/when assayed with,Multiple drugs And/or,Population types,Population Phenotypes or diseases,Multiple phenotypes or diseases And/or,Comparison Allele(s) or Genotype(s),Comparison Metabolizer types
0,1449169911,HLA-B*35:08,HLA-B,lamotrigine,29238301,Toxicity,no,The allele was not significant when comparing ...,HLA-B *35:08 is not associated with likelihood...,*35:08,NaN,NaN,Is,Not associated with,NaN,likelihood of,"Side Effect:Maculopapular Exanthema, Side Effe...",or,when treated with,NaN,in people with,Disease:Epilepsy,NaN,NaN,NaN
1,1450813230,rs1801272,CYP2A6,nicotine,22046326,Toxicity,yes,Referred to in the paper as CYP2A6*2.,Genotypes AA + AT are associated with decrease...,AA + AT,NaN,NaN,Are,Associated with,decreased,risk of,Other:Tobacco Use Disorder,NaN,due to,NaN,NaN,NaN,NaN,TT,NaN
2,1453086503,"UGT1A1*1, UGT1A1*28",UGT1A1,sacituzumab govitecan,39528547,Toxicity,yes,"""Genotype-specific analyses revealed higher in...",UGT1A1 *1/*28 + *28/*28 is associated with inc...,*1/*28 + *28/*28,NaN,NaN,Is,Associated with,increased,severity of,Side Effect:Neutropenia,NaN,when treated with,NaN,in people with,Other:Breast Neoplasms,NaN,*1/*1,NaN
3,1451833920,ABCB1 intermediate activity,ABCB1,loperamide,35815036,Toxicity,not stated,A patient with opioid use disorder showed redu...,ABCB1 intermediate activity is associated with...,NaN,NaN,intermediate activity,Is,Associated with,increased,risk of,Side Effect:Opioid-Related Disorders,NaN,when exposed to,NaN,NaN,NaN,NaN,NaN,NaN
4,1453086600,HLA-A*02:01,HLA-A,"ipilimumab, nivolumab, pembrolizumab",40155873,Toxicity,no,"""This study did not find a significant risk as...",HLA-A *02:01 is not associated with increased ...,*02:01,NaN,NaN,Is,Not associated with,increased,likelihood of,Side Effect:adverse events,NaN,when treated with,or,in people with,"Other:Melanoma, Other:Metastatic neoplasm",and,NaN,NaN

In [22]:
# Display the first five rows of the Functional Assay dataset.
functional.head()

,Variant Annotation ID,Variant/Haplotypes,Gene,Drug(s),PMID,Phenotype Category,Significance,Notes,Sentence,Alleles,Specialty Population,Assay type,Metabolizer types,isPlural,Is/Is Not associated,Direction of effect,Functional terms,Gene/gene product,When treated with/exposed to/when assayed with,Multiple drugs And/or,Cell type,Comparison Allele(s) or Genotype(s),Comparison Metabolizer types
0,1451148445,"CYP2C19*1, CYP2C19*17",CYP2C19,normeperidine,30902024,NaN,not stated,"In other in vitro experiments, normeperidine f...",CYP2C19 *17/*17 is associated with increased f...,*17/*17,NaN,in human liver microsomes,NaN,Is,Associated with,increased,formation of,NaN,NaN,NaN,NaN,*1/*1 + *1/*17,NaN
1,1448281185,"CYP2B6*1, CYP2B6*6",CYP2B6,bupropion,27439448,Efficacy,yes,The ratio of hydroxybupropion versus bupropion...,CYP2B6 *1/*1 is associated with increased acti...,*1/*1,NaN,NaN,NaN,Is,Associated with,increased,activity of,CYP2B6,when assayed with,NaN,NaN,*1/*6,NaN
2,1447944475,"CYP2C9*1, CYP2C9*2",CYP2C9,warfarin,25823787,Metabolism/PK,not stated,CYP2C9*1 formed three hydrogen bonds with warf...,CYP2C9 *2 is associated with decreased affinit...,*2,NaN,crystal structure prediction,NaN,Is,Associated with,decreased,affinity to,CYP2C9,of,NaN,NaN,*1,NaN
3,1447944483,"CYP2C9*1, CYP2C9*3",CYP2C9,warfarin,25823787,Metabolism/PK,not stated,CYP2C9*1 formed three hydrogen bonds with warf...,CYP2C9 *3 is associated with decreased affinit...,*3,NaN,crystal structure prediction,NaN,Is,Associated with,decreased,affinity to,CYP2C9,of,NaN,NaN,*1,NaN
4,1451098400,rs72552763,SLC22A1,ranitidine,29236753,Metabolism/PK,yes,"as reported for OCT1*2, with Vmax decreased by...",Allele del is associated with decreased transp...,del,NaN,Cells,NaN,Is,Associated with,decreased,transport of,NaN,NaN,NaN,NaN,GAT,NaN

### 7. Column Names
Understanding the available columns is essential for designing a future merge strategy.

In [23]:
# Display the column names in the Clinical Variants dataset.
clinical.columns

Index(['variant', 'gene', 'type', 'level of evidence', 'chemicals',
       'phenotypes'],
      dtype='str')

In [24]:
# Display the column names in the Variant Drug Annotation dataset.
drug.columns

Index(['Variant Annotation ID', 'Variant/Haplotypes', 'Gene', 'Drug(s)',
       'PMID', 'Phenotype Category', 'Significance', 'Notes', 'Sentence',
       'Alleles', 'Specialty Population', 'Metabolizer types', 'isPlural',
       'Is/Is Not associated', 'Direction of effect', 'PD/PK terms',
       'Multiple drugs And/or', 'Population types',
       'Population Phenotypes or diseases',
       'Multiple phenotypes or diseases And/or',
       'Comparison Allele(s) or Genotype(s)', 'Comparison Metabolizer types'],
      dtype='str')

In [25]:
# Display the column names in the Variant Phenotype Annotation dataset.
phenotype.columns

Index(['Variant Annotation ID', 'Variant/Haplotypes', 'Gene', 'Drug(s)',
       'PMID', 'Phenotype Category', 'Significance', 'Notes', 'Sentence',
       'Alleles', 'Specialty Population', 'Metabolizer types', 'isPlural',
       'Is/Is Not associated', 'Direction of effect',
       'Side effect/efficacy/other', 'Phenotype', 'Multiple phenotypes And/or',
       'When treated with/exposed to/when assayed with',
       'Multiple drugs And/or', 'Population types',
       'Population Phenotypes or diseases',
       'Multiple phenotypes or diseases And/or',
       'Comparison Allele(s) or Genotype(s)', 'Comparison Metabolizer types'],
      dtype='str')

In [26]:
# Display the column names in the Functional Assay dataset.
functional.columns

Index(['Variant Annotation ID', 'Variant/Haplotypes', 'Gene', 'Drug(s)',
       'PMID', 'Phenotype Category', 'Significance', 'Notes', 'Sentence',
       'Alleles', 'Specialty Population', 'Assay type', 'Metabolizer types',
       'isPlural', 'Is/Is Not associated', 'Direction of effect',
       'Functional terms', 'Gene/gene product',
       'When treated with/exposed to/when assayed with',
       'Multiple drugs And/or', 'Cell type',
       'Comparison Allele(s) or Genotype(s)', 'Comparison Metabolizer types'],
      dtype='str')

#### Observations
&emsp; The Clinical Variants dataset contains the following major concepts:

In clinicalVariants.tsv it seems that some variants are labeled based on the haplotype-based star(*) system while others use reference SNP cluster IDs (rdIDs) to avoid legacy structural conflicts. This will likely be an issue if passed directly into the machine learning pipeline, so it must be addressed.